# Run mode (debug,test,release)
RunMode = "debug"

# Print configuration parameters at startup
PrintConfig = true

# TLS Certificate Service
[TLS]
# Listening address
Host = "0.0.0.0"
# Listening port
Port = 8081
# Certificate path. If it is blank, the certificate will be issued automatically -- this certificate has two functions: 1. App service certificate; 2. As a parent certificate, used to issue certificates
CertFile = ""
# Certificate key. If it is blank, the certificate will be issued automatically -- this certificate has two functions: 1. App service certificate; 2. As a parent certificate, used to issue certificates
KeyFile = ""
# Http graceful shutdown wait timeout (unit: seconds)
ShutdownTimeout = 30
# Maximum content length allowed (64M)
MaxContentLength = 67108864
# Maximum request log length allowed for output
MaxReqLoggerLength = 1024

# Contract configuration
[Contract]
# Contract address
Address = "0x7bFb4c993F851690B253e51327ABCD7f045cd477"
# RPC Address
RpcUrl = "https://api.hyperspace.node.glif.io/rpc/v1"
# Account private key - used for signing requests
PrivateKey = "a5042f010a7d7f5652097768612265014ec390ea6f2f281f362091a5c39f4900"

# Cfssl configuration information
[Cfssl]
# configuration file
ConfigFile = "./configs/cfssl_config.json"

# Storage configuration
[Storage]
# Storage type (currently supported storage types：ipfs/web3.storage)
Type = "web3.storage"

# Ipfs storage
[Ipfs]
# Connection address
Host = "127.0.0.1"
# Connection port
Port = 5001

# Web3Storage Storage
[Web3Storage]
# Api Token
Token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6ZXRocjoweDU4MUJkZEVGNTA3MDlmZjIzQzEwN0Q5YUU2NEVlMjc5M0IyMzk3NWMiLCJpc3MiOiJ3ZWIzLXN0b3JhZ2UiLCJpYXQiOjE2NTY2NDc2MDM2MjUsIm5hbWUiOiJjbG91ZHNsaXQifQ.7iUZuCDn1SNn7CxuR_kdAWf9_PfpuJlqPmy7ZdB2x9U"
# data Encrypt key
EncryptKey = "12345678"
# Request timeout (unit/second)
Timeout = 10
# Request failed retries
RetryCount = 100

[Log]
# Log level (1:fatal 2:error,3:warn,4:info,5:debug,6:trace)
Level = 4
# Log format (support output format：text/json）
Format = "text"
# Log output (supported：stdout/stderr/file)
Output = "stdout"
# Specify the file path for log output
OutputFile = "data/app.log"
# Enable log hook
EnableHook = false
# Log level of write hook
HookLevels = ["info", "warn", "error"]
# Log hook (supported：redis)
Hook = "redis"
# Maximum number of worker threads writing hooks
HookMaxThread = 1
# Maximum number of buffers written to hook
HookMaxBuffer = 512
# Number of log polling
RotationCount = 20
# Log polling time cycle
RotationTime = 24

[LogRedisHook]
Addr = "127.0.0.1:6379"
Key = "log_key"

